### ISSUE TITLE
String Error Codes

### ISSUE THREAD

**Issue by johannesschobel** [tembra/jsonapi-errors-php#3]
Dear @tembra ,

the official [JSON API Documentation](http://jsonapi.org/format/#error-objects) specifies the structure of error objects. It reads:

> An error object MAY have the following members:
> [...]
> `code`: an application-specific error code, expressed as a string value.
> [...]

**However**, when defining an own application specific error class as described in your [wiki](https://github.com/tembra/jsonapi-errors-php/wiki/Application-Error-Codes), this error code is specified using the PHP Constants within the class, like so:

``` php
const PAGE_INVALID_PARAMETER = 1;
const RESOURCE_NOT_FOUND = 2;
const RESOURCE_UPDATE_FAILED = 3;
```

Using this construct, only **INT** values are possible for the application specific `code` of the error, although the JSON API specs explicitly says that it is _expressed as a string value_.

Considering the other issue #2 (_Best Practices for Errors_) this might be a problem. For example, I would like to "name" (give the code) `404` to the `USER_NOT_FOUND` and `GROUP_NOT_FOUND` exception. This would, however, result in 2 "similar" error codes.

Would it be possible to allow string values for the `code` of an exception? Like so:

``` php
// UserException.php
const USER_NOT_FOUND = "USER_404";
```

and

``` php
// GroupException.php
const GROUP_NOT_FOUND = "GROUP_404";
```

What do you think about this topic? Sadly, I wasn't able to dig into your code to see, how (and where) changes needs to be introduced in order to allow for `code` string values. However, if you think this would be a valuable contribution (and you do not have the time needed), I would be able to contribute!

Greetings from Germany,
Johannes

**Comment by tembra** [comment]
Hello @johannesschobel 

I got you. And also is not difficult to allow string values for `code`.

However as stated on wiki, particularly on [JSON API Error Object `code` member](https://github.com/tembra/jsonapi-errors-php/wiki/JSON-API-Error-Objects#code), it must be integer and **will be auto converted to string**.

Even that JSON API specification tell us that this needs to be a string I guess that it is not a standardize at all. Maybe they will change this in next versions. You can take a look at most common APIs that is not implementing JSON API specification but also have error codes:
- [Twitter API](https://dev.twitter.com/overview/api/response-codes)
- [Facebook Graph API](https://developers.facebook.com/docs/graph-api/using-graph-api/#errors)
- [Facebook Marketing API](https://developers.facebook.com/docs/marketing-api/error-reference)

Some others (I guess minors) use this as string like JSON API specification:
- [Google Maps API](https://developers.google.com/maps/documentation/javascript/error-messages)
- [Google DoubleClick-Search API](https://developers.google.com/doubleclick-search/v2/standard-error-responses)

Finally when documentation has been released you will get this error converted to the title they represent. So an error code `1` will be `Not Found Error!` for your developers.

For your particular example and for my application error codes I would group the codes into groups. In my applications I use group of hundreds, like `100` until `199` for group one and `200` until `299` for group two, because I do not have too different error codes through this groups. Maybe you can use groups of tens thousands, then `10000` until `19999` for  `user` group and `20000` until `29999` for `group` group. This way you can use `10404` and `20404` if you want for your example.

Indeed you still think necessary to make available give a string value to the `code` to meet the specification?

**Comment by johannesschobel** [comment]
Dear @tembra ,

yeah, i thought about this _use groups of thousands for different error code realms_ as well. Maybe I will stick to this approach - I don't know ;)

I was just curious, whats your opinion regarding this topic.. Maybe your plugin could allow for both approaches, `int` and `string` error codes. As the code is encoded as `string` value anyway, this wouldn't result in any problems.

Greetings,
Johannes

**Comment by tembra** [comment]
Yeah. I will change this today, later at night. I think it will be better.

**Comment by johannesschobel** [comment]
Thats awesome! Thanks a lot for your effort and patience ;)
